config/routes.rb
CoStickies::Application.routes.draw do
  resources :notes

  root :to => "notes#index"

end

app/models/note.rb
class Note
  include Mongoid::Document
  include Mongoid::Timestamps
  field :text, :type => String
  field :color, :type => Symbol
  COLORS = [:yellow, :green, :purple]
  validates_inclusion_of :color, :in => COLORS
  
  after_create :push_create
  after_update :push_update
  
  protected
  
  def push_create
    push_event('create')
  end
  
  def push_update
    push_event('update')
  end
  
  def push_event(event_type)
    Pusher["co-stickies-#{Rails.env}"].trigger(event_type,
                                        {:id => self.id.to_s,
                                          :text => self.text,
                                          :color => self.color})
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  # GET /notes
  # GET /notes.xml
  def index
    @notes = Note.all.order_by([:created_at, :desc]).limit(100)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @notes }
    end
  end

  # GET /notes/1
  # GET /notes/1.xml
  def show
    @note = Note.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @note }
    end
  end

  # GET /notes/new
  # GET /notes/new.xml
  def new
    @note = Note.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @note }
    end
  end

  # GET /notes/1/edit
  def edit
    @note = Note.find(params[:id])
  end

  # POST /notes
  # POST /notes.xml
  def create
    find_prime_numbers
    @note = Note.new(params[:note])

    respond_to do |format|
      if @note.save
        format.html { redirect_to(notes_url, :notice => 'Note was successfully created.') }
        format.xml  { render :xml => @note, :status => :created, :location => @note }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @note.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /notes/1
  # PUT /notes/1.xml
  def update
    @note = Note.find(params[:id])

    respond_to do |format|
      if @note.update_attributes(params[:note])
        format.html { redirect_to(notes_url, :notice => 'Note was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @note.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.xml
  def destroy
    @note = Note.find(params[:id])
    @note.destroy

    respond_to do |format|
      format.html { redirect_to(notes_url) }
      format.xml  { head :ok }
    end
  end
  
  private
  
  def find_prime_numbers
    state = Numeric.new
    print "2,3"
    (4..50000).each do
      |i|
      (2..(Math.sqrt(i).ceil)).each do
        |thing|
        state = 1
        if (i.divmod(thing)[1] == 0)
          state = 0
          break
        end
      end
      print "#{i}\," unless(state == 0)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CO Stickies</title>
  <%= stylesheet_link_tag :all %>
  <link href='http://fonts.googleapis.com/css?family=Reenie+Beanie' rel='stylesheet' type='text/css'>


  <%= javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js', 
                             'http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.4/jquery-ui.min.js',
                             'http://js.pusherapp.com/1.6/pusher.min.js' %>
  
  <script type="text/javascript">
    var pusher_key = "<%= Pusher.key %>";
    var pusher_channel = "co-stickies-<%= Rails.env %>";
  </script>



  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :color %><br />
    <%= f.collection_select(:color, Note::COLORS, :to_s, :to_s) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/_note.html.erb
<li id="<%= note.id  %>" class="note <%= note.color %>">
	<p><%= sanitize auto_link note.text %></p>
	<span><%= link_to 'Edit', edit_note_path(note) %></span>
</li>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<h1>CO Stickies</h1>

<%= link_to 'New Note', new_note_path %>

<ul id="notes">
	<%= render @notes %>
</ul>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Text:</b>
  <%= @note.text %>
</p>


<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>